#!/usr/bin/env python3
"""
Push a local trained model directory to Hugging Face Hub.

Intended for the Writing7 book matcher checkpoints produced by this repo.

Recommended usage (keeps repo layout expected by our inference code):

  python scripts/push_to_hf.py \
    --repo-id your-org/writing7-book-matcher-contrastive-v1 \
    --source-dir models/book_matcher_contrastive

This uploads the entire folder so the Hub repo root contains:
  - final/  (weights + tokenizer)
  - calibration.json
  - style_calibration.json (optional)

For the cross-encoder baseline:

  python scripts/push_to_hf.py \
    --repo-id your-org/writing7-book-matcher-cross-encoder-v1 \
    --source-dir models/book_matcher

Requires:
  pip install huggingface_hub
  huggingface-cli login
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Optional


def _ensure_hf():
    try:
        import huggingface_hub  # noqa: F401
    except Exception:
        print("ERROR: huggingface_hub is not installed. Run: pip install huggingface_hub", file=sys.stderr)
        sys.exit(2)


def _default_card(source: Path, title: str) -> str:
    # Minimal model card with metadata; users can edit later on the Hub
    return f"""
---
license: apache-2.0
language: en
tags:
  - style-transfer
  - evaluation
  - book-matching
  - transformers
library_name: transformers
---

# {title}

This repository contains trained weights produced by the Writing7 project.

Layout:
- `final/`: model weights and tokenizer files saved by `Trainer.save_model(...)`.
- `calibration.json`: temperature and threshold selected on validation data.
- `style_calibration.json` (optional): mapping from cosine similarity to [0,1] probability.

## Usage

Download locally and point the benchmark scorer at `final/`:

```python
from huggingface_hub import snapshot_download
from inference_contrastive import ContrastiveBookMatcherInference

local = snapshot_download(repo_id="REPO_ID")
scorer = ContrastiveBookMatcherInference(model_path=f"{local}/final")
```

Refer to the GitHub repo for the full benchmark harness.
""".strip()


def push_to_hub(repo_id: str, source_dir: str, private: bool = False, card_title: Optional[str] = None) -> None:
    from huggingface_hub import HfApi, upload_folder, create_repo

    src = Path(source_dir).resolve()
    if not src.exists():
        raise FileNotFoundError(f"source dir not found: {src}")

    # If pointed directly at .../final, switch to parent so we upload final/ under repo root
    if src.name == "final":
        src = src.parent

    final_dir = src / "final"
    if not final_dir.exists() or not final_dir.is_dir():
        raise FileNotFoundError(f"expected 'final/' inside {src}. Got: {final_dir} (missing)")

    # Create repo if needed
    create_repo(repo_id=repo_id, repo_type="model", exist_ok=True, private=private)

    # Upload all contents of source dir to repo root (exclude VCS)
    ignore = [".git/*", "**/__pycache__/*", ".DS_Store"]
    upload_folder(repo_id=repo_id, folder_path=str(src), path_in_repo=".", ignore_patterns=ignore)

    # Ensure a simple README exists (model card)
    readme = src / "README.md"
    if not readme.exists():
        title = card_title or Path(repo_id).name
        content = _default_card(src, title)
        # Upload the generated README directly
        api = HfApi()
        api.upload_file(
            repo_id=repo_id,
            path_or_fileobj=content.encode("utf-8"),
            path_in_repo="README.md",
        )

    print(f"Pushed to https://huggingface.co/{repo_id}")


def main():
    _ensure_hf()
    p = argparse.ArgumentParser()
    p.add_argument("--repo-id", required=True, help="<org-or-user>/<name>")
    p.add_argument("--source-dir", required=True, help="Directory containing 'final/' and calibration files")
    p.add_argument("--private", action="store_true", help="Create the Hub repo as private")
    p.add_argument("--title", default=None, help="Optional title for autogenerated README.md")
    args = p.parse_args()
    push_to_hub(args.repo_id, args.source_dir, private=args.private, card_title=args.title)


if __name__ == "__main__":
    main()

